const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"出售房屋类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChushoufangwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"区域管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryQuyu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"出租房屋类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZufang"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"租房管理",
                        "menuJump":"列表",
                        "tableName":"zufang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"租房留言管理",
                        "menuJump":"列表",
                        "tableName":"zufangLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"租房收藏管理",
                        "menuJump":"列表",
                        "tableName":"zufangCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "审核",
                            "查看"
                        ],
                        "menu":"预约租房看房管理",
                        "menuJump":"列表",
                        "tableName":"zufangOrder"
                    }
                ],
                "menu":"租房管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出售房屋管理",
                        "menuJump":"列表",
                        "tableName":"chushoufangwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"出售房屋留言管理",
                        "menuJump":"列表",
                        "tableName":"chushoufangwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"出售房屋收藏管理",
                        "menuJump":"列表",
                        "tableName":"chushoufangwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "审核",
                            "查看"
                        ],
                        "menu":"预约出售房屋看房管理",
                        "menuJump":"列表",
                        "tableName":"chushoufangwuOrder"
                    }
                ],
                "menu":"出售房屋管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"租房管理",
                        "menuJump":"列表",
                        "tableName":"zufang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"租房留言管理",
                        "menuJump":"列表",
                        "tableName":"zufangLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"租房收藏管理",
                        "menuJump":"列表",
                        "tableName":"zufangCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "审核",
                            "查看"
                        ],
                        "menu":"预约租房看房管理",
                        "menuJump":"列表",
                        "tableName":"zufangOrder"
                    }
                ],
                "menu":"租房管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出售房屋管理",
                        "menuJump":"列表",
                        "tableName":"chushoufangwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"出售房屋留言管理",
                        "menuJump":"列表",
                        "tableName":"chushoufangwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"出售房屋收藏管理",
                        "menuJump":"列表",
                        "tableName":"chushoufangwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "审核",
                            "查看"
                        ],
                        "menu":"预约出售房屋看房管理",
                        "menuJump":"列表",
                        "tableName":"chushoufangwuOrder"
                    }
                ],
                "menu":"出售房屋管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
